apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv-0
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: "rabbitmq-pv-0" # this is the unique identifier of the PV configured using SMB CSI driver
    volumeAttributes:
      source: "//192.168.0.102/db"
    nodeStageSecretRef:
      name: smb-secret
      namespace: rabbitmq-system-customized
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: "rabbitmq-pv-1" # this is the unique identifier of the PV configured using SMB CSI driver
    volumeAttributes:
      source: "//192.168.0.102/db"
    nodeStageSecretRef:
      name: smb-secret
      namespace: rabbitmq-system-customized
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv-2
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: "rabbitmq-pv-2" # this is the unique identifier of the PV configured using SMB CSI driver
    volumeAttributes:
      source: "//192.168.0.102/db"
    nodeStageSecretRef:
      name: smb-secret
      namespace: rabbitmq-system-customized
